steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function_cicd
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python312
  - --allow-unauthenticated

serviceAccount: "cicd-sa@storied-core-424404-t8.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
